# Generated by Django 5.2.5 on 2025-09-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userprofile'),
        ),
    ]
