# Generated by Django 5.2.5 on 2025-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_post_likes_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
            ],
        ),
    ]
