# Generated by Django 5.2.5 on 2025-09-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField()),
                ('document', models.FileField(upload_to='pdfs/')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyname', to='mainapp.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyposition', to='mainapp.company')),
            ],
        ),
    ]
