# Generated by Django 5.2.5 on 2025-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_forapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='des',
            field=models.TextField(default=True),
        ),
    ]
