# Generated by Django 5.2.5 on 2025-09-17 05:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
