# Generated by Django 5.2.5 on 2025-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='Company_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='des',
            new_name='Des',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='education',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='position',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='forapply',
            old_name='company_name',
            new_name='Company_name',
        ),
        migrations.RenameField(
            model_name='forapply',
            old_name='document',
            new_name='Document',
        ),
        migrations.RenameField(
            model_name='forapply',
            old_name='position',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='education',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='company',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='des',
        ),
        migrations.AddField(
            model_name='forapply',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='forapply',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Coures',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Hobbies',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forapply',
            name='Education',
            field=models.CharField(null=True),
        ),
    ]
