# Generated by Django 5.2.5 on 2025-09-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_rename_company_name_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Coures',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Hobbies',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
