# Generated by Django 5.2.5 on 2025-09-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_userprofile_coures_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
    ]
