# Generated by Django 5.2.5 on 2025-09-17 10:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_rename_user_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
