# Generated by Django 5.2.5 on 2025-09-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_userprofile_address_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Des',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Salary',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='Document',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='Position',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forapply',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='forapply',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('education_required', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='mainapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='forapply',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='forapply',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='forapply',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='forapply',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.position'),
        ),
    ]
