# Generated by Django 5.2.5 on 2025-09-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_remove_company_company_name_remove_company_des_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forapply',
            name='position',
        ),
        migrations.RenameField(
            model_name='forapply',
            old_name='document',
            new_name='Document',
        ),
        migrations.RenameField(
            model_name='forapply',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='company',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='forapply',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='company',
            name='Company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Des',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forapply',
            name='Company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applyname', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='forapply',
            name='Education',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='forapply',
            name='Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applyposition', to='mainapp.company'),
        ),
        migrations.AddField(
            model_name='forapply',
            name='Phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
