# Generated by Django 5.2.5 on 2025-09-17 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_remove_forapply_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Des',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Salary',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, null=True)),
                ('education', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='mainapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('resume', models.FileField(null=True, upload_to='resumes/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.job')),
            ],
        ),
        migrations.DeleteModel(
            name='Forapply',
        ),
    ]
