# Generated by Django 5.2.5 on 2025-09-18 11:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='untitled', max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
