# Generated by Django 5.2.5 on 2025-09-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_job_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
    ]
